# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurant',
            new_name='RestaurantModel',
        ),
    ]
