# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0002_auto_20170220_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantmodel',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
