# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0006_auto_20170223_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurant',
            field=models.ManyToManyField(null=True, to='resapp.RestaurantModel'),
        ),
    ]
